services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG-main} 
    volumes:
      - ui-storage:/app/backend/data
    ports:
      - ${OPEN_WEBUI_PORT-8080}:8080
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped


  #   environment:
  #     ENABLE_RAG_WEB_SEARCH: True
  #     RAG_WEB_SEARCH_ENGINE: "searxng"
  #     RAG_WEB_SEARCH_RESULT_COUNT: 3
  #     RAG_WEB_SEARCH_CONCURRENT_REQUESTS: 10
  #     SEARXNG_QUERY_URL: "http://searxng:8080/search?q=<query>"
 
  # searxng:
  #   image: searxng/searxng:latest
  #   container_name: searxng
  #   ports:
  #     - "8090:8080"
  #   volumes:
  #     - ./searxng:/etc/searxng
  #   restart: always

volumes:
  ui-storage: {}
